name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # Desabilitar cache para forçar instalação limpa
        cache: 'none'

    - name: Clear npm cache and remove existing files
      run: |
        npm cache clean --force
        rm -rf node_modules
        rm -f package-lock.json
        rm -rf .npm

    - name: Install dependencies with legacy peer deps
      run: npm ci --legacy-peer-deps --no-audit

    - name: Setup Prisma
      run: npx prisma generate

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        # Variáveis de ambiente necessárias para o build
        DATABASE_URL: ${{ secrets.DATABASE_URL || 'postgresql://dummy:dummy@localhost:5432/dummy' }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'dummy-secret-key-for-build-only' }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY || 'dummy-key' }}
        SECURITY_HEADERS_ENABLED: 'true'
        RATE_LIMIT_ENABLED: 'true'
        SECURITY_LOGGING_ENABLED: 'true'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: .next/ 