name: Fix Node Setup Issue

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: .

    # Configurar pnpm ANTES do setup-node para evitar conflitos
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    # Setup Node.js SEM cache automático para evitar o erro
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # NÃO usar cache automático aqui para evitar conflitos

    # Cache manual do pnpm
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    # Cache do Next.js
    - name: Setup Next.js cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

    # Listar arquivos para depuração
    - name: List files
      run: ls -l

    # Verificar se pnpm-lock.yaml existe
    - name: Check for pnpm-lock.yaml
      run: |
        if [ -f "pnpm-lock.yaml" ]; then
          echo "pnpm-lock.yaml found, using --frozen-lockfile"
          echo "USE_FROZEN=true" >> $GITHUB_ENV
        else
          echo "pnpm-lock.yaml not found, using --no-frozen-lockfile"
          echo "USE_FROZEN=false" >> $GITHUB_ENV
        fi

    # Instalar dependências com fallback
    - name: Install dependencies (frozen)
      if: env.USE_FROZEN == 'true'
      run: pnpm install --frozen-lockfile

    - name: Install dependencies (no frozen)
      if: env.USE_FROZEN == 'false'
      run: pnpm install --no-frozen-lockfile

    - name: Build application
      run: pnpm build
      env:
        NODE_ENV: production
        DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'
        NEXTAUTH_SECRET: 'dummy-secret-key-for-build-only'
        NEXTAUTH_URL: 'http://localhost:3000'
        OPENROUTER_API_KEY: 'dummy-key'
        SECURITY_HEADERS_ENABLED: 'true'
        RATE_LIMIT_ENABLED: 'true'
        SECURITY_LOGGING_ENABLED: 'true'

    - name: Success
      run: echo "✅ Build completed successfully without setup-node cache issues!" 